# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qsu8me60EwizE_729zAeUBNQuNQRaQp2
"""

import sys
import os
import random
import time
import tkinter
from tkinter import *

window = tkinter.Tk()
window.title("Adventure Game")

window.geometry("966x700")
window.minsize(width=966, height=700)
# window.maxsize(width=966, height=700)

frame = Frame(window)
frame.pack()


# Getting and setting up image
from PIL import ImageTk, Image
img = ImageTk.PhotoImage(Image.open("Cave2.png"))

# Loading Background Image
label = tkinter.Label(frame, image=img)
label.pack()

l1 = tkinter.Label(frame, text="WELCOME TO OUR ADVERNTURE GAME")
l1.pack()

# l2 = tkinter.Label(frame, text="HEALTH = 100", bg="Black", fg="White")
# l2.pack()



# Creatig Button function
def create_btn(str, cmd):
    btn = tkinter.Button(frame, width=15, height=1, text=str, command=cmd)
    return btn

# Creating Yes and No Buttons
yes_1 = create_btn("YES", "")
no_1 = create_btn("NO", "")

# Healt Bar
l2 = tkinter.Label(frame, text="HEALTH = 100", bg="Black", fg="White")

# Clearin Frame of all widets
def clear_frame():
   for widgets in frame.winfo_children():
      widgets.destroy()

def change_img(str):
   img2=ImageTk.PhotoImage(Image.open(str))
   label.configure(image=img2)
   label.image=img2




def Entry():
    b1.destroy()
    
    l2.pack()
    l1.config(text="You are in a dark cave. The entry has been sealed by fallen rocks. There is no way out. Ahead, you can see a door. Will you continue?")



    # yes_1 = tkinter.Button(frame, width=15, height=1, text="YES" command=Kick)
    yes_1.configure(command=yes_kick)
    yes_1.pack()
    

    no_1.configure(command=no_kick)
    no_1.pack()



def yes_kick():
    change_img("door.png")
    l1.config(text="Door is opened by kick. Contains fast wind. Hero crawls to groung and reach end. Will you crawl?")
    yes_1.configure(command=Door)
    # yes_1.pack()

def no_kick():
    change_img("bat.png")
    l1.config(text="A bat flies over your head and you hear screetches in the distance. You sit in total darkness wondering if there's a way out.")


def Door():
    change_img("Lake2.png")
    l1.config(text="It's a long lake and there are two crocodiles in it. Ahead, you can see a rope. Will you swing from rope to get to end point?")
    l2.pack()
    no_1.configure(command=no_Door)
    yes_1.configure(command=Alarming)

def no_Door():
    l1.config(text="You are injured because crocodile hits you. You are thinking any other way except using rope.")
    l2.pack()

def Alarming():
    change_img("sand_dune.png")
    l1.config(text="Space contains fire with sand dunes. Hero puts off fire with sand. Will you do this?")
    l2.pack()
    no_1.configure(command=no_Alarming)
    yes_1.configure(command=Cavern)

def no_Alarming():
    l1.config(text="Your one leg and arm has burned because of fire.")
    l2.pack()


def Cavern():
    change_img("Cavern.png")
    l1.config(text="You stumble into a dimly lit cavern. You cannot go right or left but the cave continues ahead. Will you go on?")
    l2.pack()
    no_1.configure(command=no_Cavern)
    yes_1.configure(command=Hallway)

def no_Cavern():
    l1.config(text="You sit down and eat some food you brought with you.")
    l2.pack()

def Hallway():
    change_img("hallway.png")
    l1.config(text="You are in a wide hallway. It continues on indefinitely. There's no turning back. Will you go on?")
    l2.pack()
    no_1.configure(command=no_Hallway)
    yes_1.configure(command=Pit)

def no_Hallway():
    l1.config(text="You try to call your help but no one is there.")
    l2.pack()

def Pit():
    change_img("Pit.png")
    l1.config(text="You fall head first into an ominous and languid pit. Luckly, you only landed on your back. You can try to climb out. Will you try?")
    l2.pack()
    no_1.configure(command=no_Pit)
    yes_1.configure(command=Gold)

def no_Pit():
    l1.config(text="You sit in utter darkness.")
    l2.pack()

def Gold():
    change_img("Gold.png")
    l1.config(text="You reached to your final destination.Finally, you can see gold. You can take the gold. Will you take?")
    l2.pack()
    no_1.configure(command=Lose)
    yes_1.configure(command=Win)


def Lose():
    change_img("Lose.png")
    l1.config(text="You did not take the Gold. GAME OVER!")

def Win():
    change_img("Win.png")
    l1.config(text="You took enough gold. GAME OVER!")
    l2.pack()

b1 = tkinter.Button(frame, width=15, height=3, text="START", command=Entry)
b1.pack()



window.mainloop()

class Game:

    def print_slow(self, str, delay=0.1):
        for letter in str:
            sys.stdout.write(letter)
            sys.stdout.flush()
            time.sleep(delay)
        print("\n")


    def reset_console(self):
        print("\n")
        os.system('cls||clear')


    def fprint(self, str, delay=0):
        print("\n" + str)
        time.sleep(delay)


    def sprint(self, str, delay=0):
        print(str)
        time.sleep(delay)


game_functions = Game()


class player:
    def __init__(self, location, health, items):
        self.location = location
        self.health = health
        self.items = items

hero = player("entry", 100, [])


class NPC:
    def __init__(self, name, location):
        self.name = name
        self.location = location

    def talk(self):
        game_functions.fprint(f"A {self.name} emerges from the shadows.")
        game_functions.fprint("'Hisssss! Stay away from me!'")

    def move(self):
        available_locations = ["entry", "door", "lake", "alarming", "cavern", "hallway", "pit", "gold"]
        self.location = random.choice(available_locations)


goblin = NPC("goblin", "hallway")


class World:

    def entry(self):
        hero.location = "entry"
        print(f"\nHealth: {hero.health}")
        game_functions.fprint("You are in a dark cave. The entry has been sealed by fallen rocks. There is no way out.", 2)
        print("Ahead, you can see a door. Will you continue?")
        print("Enter 'yes' or 'no'.")
        self.check_medkit()
        self.handle_goblin()
        while True:
            action = input("\n> ")
            if action == "yes":
                self.door()
            elif action == "no":
                game_functions.fprint("A bat flies over your head and you hear screetches in the distance.")
            elif action == "m":
                self.use_medkit()
            else:
                game_functions.fprint("You sit in total darkness wondering if there's a way out.")

    def door(self):
        hero.location = "door"
        print(f"\nHealth: {hero.health}")
        game_functions.fprint("Door is opened by kick. Contains fast wind.", 2)
        print("Hero crawls to groung and reach end. Will you crawl?")
        print("Enter 'yes' or 'no'.")
        self.check_medkit()
        self.handle_goblin()
        while True:
            action = input("\n> ")
            if action == "yes":
                self.lake()
            elif action == "no":
                game_functions.fprint("You hear loud voices of wind.")
            elif action == "m":
                self.use_medkit()
            else:
                game_functions.fprint("You are scare of voices.")

    def lake(self):
        hero.location = "lake"
        print(f"\nHealth: {hero.health}")
        game_functions.fprint("It's a long lake and there are two crocodiles in it.", 2)
        print("Ahead, you can see a rope. Will you swing from rope to get to end point?")
        print("Enter 'yes' or 'no'.")
        self.check_medkit()
        self.handle_goblin()
        while True:
            action = input("\n> ")
            if action == "yes":
                self.alarming()
            elif action == "no":
                game_functions.fprint("You are injured because crocodile hits you.")
            elif action == "m":
                self.use_medkit()
            else:
                game_functions.fprint("You are thinking any other way except using rope.")

    def alarming(self):
        hero.location = "alarming"
        print(f"\nHealth: {hero.health}")
        game_functions.fprint("Space contains fire with sand dunes.", 2)
        print("Hero puts off fire with sand. Will you do this?")
        print("Enter 'yes' or 'no'.")
        self.check_medkit()
        while True:
            action = input("\n> ")
            if action == "yes":
                self.cavern()
            elif action == "no":
                game_functions.fprint("Your one leg and arm has burned because of fire.")
            elif action == "m":
                self.use_medkit()
            else:
                game_functions.fprint("You are feeling very hot.")

    def cavern(self):
        hero.location = "cavern"
        print(f"\nHealth: {hero.health}")
        game_functions.fprint("You stumble into a dimly lit cavern.", 2)
        print("You cannot go right or left but the cave continues ahead. Will you go on?")
        print("Enter 'yes' or 'no'.")
        self.check_bat_attack()
        self.handle_goblin()
        while True:
            action = input("\n> ")
            if action == "yes":
                self.hallway()
            elif action == "no":
                game_functions.fprint("You sit down and eat some food you brought with you.")
            elif action == "m":
                self.use_medkit()
            else:
                game_functions.fprint("You shiver from the cold.")

    def hallway(self):
        hero.location = "hallway"
        print(f"\nHealth: {hero.health}")
        game_functions.fprint("You are in a wide hallway. It continues on indefinitely.", 2)
        print("There's no turning back. Will you go on?")
        print("Enter 'yes' or 'no'.")
        self.handle_goblin()
        while True:
            action = input("\n> ")
            if action == "yes":
                self.pit()
            elif action == "no":
                game_functions.fprint("You try to call your help but no one is there.")
            elif action == "m":
                self.use_medkit()
            else:
                game_functions.fprint("You wonder what time it is.")

    def pit(self):
        hero.location = "pit"
        print(f"\nHealth: {hero.health}")
        game_functions.fprint("You fall head first into an ominous and languid pit. Luckly, you only landed on your back", 2)
        print("You can try to climb out. Will you try?")
        print("Enter 'yes' or 'no'.")
        self.handle_goblin()
        while True:
            action = input("\n> ")
            if action == "yes":
                self.gold()
            elif action == "no":
                game_functions.fprint("You sit in utter darkness.")
            elif action == "m":
                self.use_medkit()
            else:
                game_functions.fprint("You feel hopeless.")

    def gold(self):
        hero.location = "gold"
        print(f"\nHealth: {hero.health}")
        game_functions.fprint("You reached to your final destination.", 2)
        game_functions.sprint("Finally, you can see gold.", 2)
        print("You can take the gold. Will you take?")
        print("Enter 'yes' or 'no'.")
        while True:
            action = input("\n> ")
            if action == "yes":
                game_functions.fprint("You take enough gold.", 2)
                print("GAME OVER.")
                sys.exit()
            elif action == "no":
                game_functions.fprint("You don't find the gold, you lose.")
            elif action == "m":
                self.use_medkit()
            else:
                game_functions.fprint("You give up.")




    def use_medkit(self):
        if "medkit" in hero.items:
            hero.items.remove("medkit")
            game_functions.fprint("You used your medkit")
            hero.health = 100
            print(f"\nHealth: {hero.health}")
        else:
            game_functions.fprint("You don't have a medkit.")


    def handle_goblin(self):
        goblin.move()
        if hero.location == goblin.location:
            goblin.talk()


    def check_medkit(self):
        medkit_find = random.choice([True, False])
        if medkit_find is True:
            hero.items.append("medkit")
            game_functions.fprint("You found a medkit!", 2)
            print("Enter 'm' to use it.")


    def check_bat_attack(self):
        bat_attack = random.choice([True, False])
        if bat_attack is True:
            game_functions.fprint("You were attacked by a bat!", 2)
            hero.health -= random.randint(1, 100)
            print(f"\nHealth: {hero.health}")
            if hero.health == 0:
                game_functions.fprint("You are dead!")
                sys.exit()


new_world = World()


new_world.entry()